version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backtest-importer-prod
    tty: true
    # ports: 
    #   - 8888:8888
  database:
    container_name: backtest-pg
    image: postgres
    volumes:
      - ./db-backup:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=DoCkEr!!  # Substitua por seu nome de usuário
      - POSTGRES_PASSWORD=BaCkTeSt!!  # Substitua por sua senha
      - POSTGRES_DB=backtest  # Substitua pelo nome do seu banco de dados
  queue-cache:
    container_name: backtest-queue-redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - backtest-net

networks:
  backtest-net:
    driver: bridge